wiki/urls.py
from django.urls import path
from . import views


app_name = 'wiki'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('issues/<int:pk>/', views.DetailViewDiscussion.as_view(), name='issue'),
    path('argument/<int:pk>/', views.DetailViewArgument.as_view(), name='argument'),
    path('premise/<int:pk>/', views.DetailViewPremises.as_view(), name='premises'),
    path('conclusion/<int:pk>/', views.DetailViewConclusion.as_view(), name='conclusion'),
    path('category/<int:pk>/', views.DetailViewCategory.as_view(), name='category'),
    path('news/<int:pk>/', views.DetailViewKeyword.as_view(), name='news'),
    path('update', views.update, name='update'),
    path('search', views.ArgumentSearchList.as_view(), name='search'),
]

wiki/models.py
from django.db import models
from .formular import *


# Create your models here.


class Issue(models.Model):
    id = models.IntegerField(primary_key=True)
    issue_title = models.CharField(max_length=300)
    issue_info = models.TextField(max_length=500)
    lang = models.TextField(max_length=10)


class Position(models.Model):
    id = models.IntegerField(primary_key=True)
    issue = models.ManyToManyField(Issue)
    statement = models.ForeignKey('Statement', on_delete=models.CASCADE, related_name='statement_position')
    statement_below = models.ManyToManyField('Statement', related_name='statementsBelow')
    acceptance_score = models.FloatField(null=True)

    def __str__(self):
        return self.statement.__str__()

    def position_acceptance(self):
        self.statement.statement_acceptance()
        self.acceptance_score = self.statement.acceptance * 100
        self.save()


class Argument(models.Model):
    id = models.IntegerField(primary_key=True)
    text = models.TextField(null=True)
    upVotes = models.IntegerField()
    context_assessment = models.BooleanField()
    downVotes = models.IntegerField()
    lang = models.TextField()
    isSupportive = models.BooleanField()
    date = models.DateTimeField()
    under_position = models.ManyToManyField(Position)
    keywords = models.ManyToManyField('Keyword')
    concepts = models.ManyToManyField('Concept')
    categories = models.ManyToManyField('Category')
    information = models.ManyToManyField('Information')
    emotion = models.ForeignKey('Emotion', on_delete=models.CASCADE, null=True)
    attacked_argument = models.ForeignKey('Argument',
                                          on_delete=models.CASCADE,
                                          related_name='attackedargument',
                                          null=True)
    conclusion = models.ForeignKey('Conclusion',
                                   on_delete=models.CASCADE,
                                   null=True)
    premise_group = models.ForeignKey('PremiseGroup', on_delete=models.CASCADE)
    type = models.TextField(null=True)
    type_text = models.TextField(null=True)
    argument_acceptance = models.FloatField(null=True)
    conclusion_acceptability = models.FloatField(null=True)
    f_r_ease = models.IntegerField(null=True)
    ari = models.IntegerField(null=True)
    sound = models.FilePathField(null=True)
    sentiment_accuracy = models.FloatField(null=True)

    def plain_string(self):
        premise = self.premise_group.__str__()
        conclusion = self.conclusion.__str__()
        if self.conclusion is None:
            conclusion = '. ' + self.attacked_argument.plain_string()
        return premise + ' ' + conclusion

    def __str__(self):
        premise = self.premise_group.__str__()
        conclusion = self.conclusion.__str__()
        if self.conclusion is None:
            conclusion = self.attacked_argument.__str__()
        return self.type_text.join([premise, conclusion])

    @property
    def save_text(self):
        self.text = 'Regarding that ' + self.__str__()
        self.save()

    @property
    def sentiment(self):
        if self.sentiment_accuracy == 0:
            return 'neutral'
        if self.sentiment_accuracy > 0.0:
            return 'positive'
        else:
            return 'negative'

    @property
    def acceptance(self):
        return self.argument_acceptance * 100

    @property
    def attacked_by(self):
        return Argument.objects.filter(attacked_argument=self)

    @property
    def under_issues(self):
        issues = []
        for pos in self.under_position.all():
            for issue in pos.issue.all():
                issues.append(issue)
        return list(set(issues))

    def has_full_information(self):
        for information in self.information.all():
            if information.full:
                return True
        return False

    def has_ambi_information(self):
        for information in self.information.all():
            if information.ambivalent:
                return True
        return False

    def conclusion_acceptability(self):
        self.premise_group.premise_acceptance()
        return self.premise_group.premise_group_acceptance * self.conditional_acceptability()

    def conditional_acceptability(self):
        c_a = 1
        for argument in self.attacked_by:
            argument.conclusion_acceptability()
            c_a = reliability(c_a, argument.conclusion_acceptability())
        return c_a

    def argument_acceptability(self):
        self.argument_acceptance = self.conclusion_acceptability()
        if self.isSupportive is False:
            self.argument_acceptance = 1 - self.argument_acceptance
        self.save()


class Statement(models.Model):
    id = models.IntegerField(primary_key=True)
    isPosition = models.BooleanField()
    lang = models.TextField()
    new_calculation = models.IntegerField(default=0)
    statement_text = models.TextField(null=True)
    acceptance = models.FloatField(null=True)

    def __str__(self):
        return self.statement_text

    def statement_acceptance(self):
        if self.conclusion_set.all().first() is not None:
            self.new_calculation += 1
            if self.new_calculation >= 2:
                self.acceptance = 0.5
            else:
                self.conclusion_set.all().first().conclusion_acceptance()
                self.acceptance = self.conclusion_set.all().first().conclusion_acceptability
        else:
            self.acceptance = 0.75
        self.save()


class Conclusion(models.Model):
    id = models.IntegerField(primary_key=True)
    rebuts = models.IntegerField()
    supports = models.IntegerField()
    undercuts = models.IntegerField()
    statement = models.ForeignKey(Statement, on_delete=models.CASCADE)
    information = models.ManyToManyField('Information')
    inference_score = models.FloatField(null=True)
    conclusion_acceptability = models.FloatField(null=True)

    def __str__(self):
        return self.statement.__str__()

    @property
    def positive_inference(self):
        return self.argument_set.all().filter(isSupportive=True).count()

    @property
    def negative_inference(self):
        return self.argument_set.all().exclude(isSupportive=True).count()

    def con_convergent(self):
        result = 0.5
        for argument in self.argument_set.all().filter(isSupportive=False):
            argument.argument_acceptability()
            if argument.argument_acceptance < 0.5:
                result = 1 - acceptability(1 - result, 1 - argument.argument_acceptance)
        return result

    def pro_convergent(self):
        result = 0.5
        for argument in self.argument_set.all().filter(isSupportive=True):
            argument.argument_acceptability()
            if argument.argument_acceptance > 0.5:
                result = acceptability(result, argument.argument_acceptance)
        return result

    def conductive(self):
        strength_pro = self.pro_convergent()
        strength_con = self.con_convergent()
        if strength_pro == 1:
            return 1
        if strength_con == 0:
            return 0
        if strength_pro == 1 and strength_con == 0:
            return None
        return strength_pro + strength_con - (1 / 2)

    def conclusion_acceptance(self):
        n_of_arguments = self.argument_set.all().count()  # rebuts+supports+undercuts
        n_of_supports = self.argument_set.all().filter(isSupportive=True).count()  # supports
        if n_of_arguments is 1:
            self.argument_set.first().conclusion_acceptability()
        if n_of_arguments == n_of_supports:
            self.conclusion_acceptability = self.pro_convergent()
        if n_of_supports == 0:
            self.conclusion_acceptability = self.con_convergent()
        if n_of_arguments != n_of_supports:
            self.conclusion_acceptability = self.conductive()
        self.save()


class PremiseGroup(models.Model):
    id = models.IntegerField(primary_key=True)
    information = models.ManyToManyField('Information')
    positive_inference = models.IntegerField(null=True)
    negative_inference = models.IntegerField(null=True)
    ratio_inference = models.FloatField(null=True)
    premise_group_acceptance = models.FloatField(null=True)

    def __str__(self):
        return ', '.join([premise.__str__() for premise in self.premise_set.all()])

    def premise_acceptance(self):
        score = 1
        for premise in self.premise_set.all():
            premise.statement.statement_acceptance()
            score *= premise.statement.acceptance
        if score <= 0.5:
            score = 0.5
        self.premise_group_acceptance = score
        self.save()


class Premise(models.Model):
    id = models.IntegerField(primary_key=True)
    premiseGroup = models.ForeignKey(PremiseGroup, on_delete=models.CASCADE)
    statement = models.ForeignKey(Statement, on_delete=models.CASCADE)

    def __str__(self):
        return self.statement.__str__()


class Information(models.Model):
    id = models.IntegerField(primary_key=True)
    word = models.TextField()
    title = models.TextField()
    description = models.TextField(null=True)
    summary = models.TextField(null=True)
    link = models.TextField()
    fullInfo = models.BooleanField(null=True)
    acad_score = models.ForeignKey('AcadScore', null=True, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.word).replace("_", " ")

    @property
    def full(self):
        return Information.objects.filter(id=self.id).exclude(summary=None)

    @property
    def ambivalent(self):
        return Information.objects.filter(id=self.id).filter(summary=None)


class AcadScore(models.Model):
    his = models.DecimalField(decimal_places=2, max_digits=4)
    edu = models.DecimalField(decimal_places=2, max_digits=4)
    soc = models.DecimalField(decimal_places=2, max_digits=4)

wiki/templates/wiki/detailCategory.html
<!DOCTYPE html>
<html lang="en">
<head>
        <meta charset="utf-8">
     <meta name="viewport" content="width=device-width, initial-scale=1"> <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'wiki/style.min.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
    <title>{{categorylabel}}</title>
</head>
    <div class="container">
    <h1>{{categorylabel}}</h1>
        <p><hr>
    <dl>
        <h2>High relevance for this Category</h2>
        <div class="well well-sm">
        {% for category in categorylabel.category_set.all %}
            {% if category.relevance >= 0.9 %}
            {% for argument in category.argument_set.all %}
           <dd><a href = "{% url 'wiki:argument' argument.id %}"><i  class="fa fa-comment-o" aria-hidden="true"></i></a>
                <span class="text-muted">Regarding that</span>
                <a href="{% url 'wiki:premises' argument.premise_group.id %}"><font color="#ee82ee">{{argument.premise_group}}</font></a>
                {% if argument.isSupportive %}
                 <span class="text-success">{{argument.type_text}}</span>
                {% else %}
                <span class="text-danger">{{argument.type_text}}</span>
                {% endif %}
                {% if argument.conclusion %}
                <a href="{% url 'wiki:conclusion' argument.conclusion.id %}" class="text-secondary">{{argument.conclusion}}</a>
                {% else %}
                    <a href = "{% url 'wiki:argument' argument.attacked_argument.id %}" class="text-muted">{{argument.attacked_argument}}</a>
                {% endif %}
            </dd>
            {% endfor %}
            {% endif %}
            {% endfor %}
            </div>
        <h2>Medium relevance for this Category</h2>
        <div class="well well-sm">
    {% for category in categorylabel.category_set.all %}
        {% if category.relevance > 0.7 and category.relevance < 0.9 %}
        {% for argument in category.argument_set.all %}
       <dd><a href = "{% url 'wiki:argument' argument.id %}"><i  class="fa fa-comment-o" aria-hidden="true"></i></a>
            <span class="text-muted">Regarding that</span>
            <a href="{% url 'wiki:premises' argument.premise_group.id %}"><font color="#ee82ee">{{argument.premise_group}}</font></a>
            {% if argument.isSupportive %}
             <span class="text-success">{{argument.type_text}}</span>
            {% else %}
            <span class="text-danger">{{argument.type_text}}</span>
            {% endif %}
            {% if argument.conclusion %}
            <a href="{% url 'wiki:conclusion' argument.conclusion.id %}" class="text-secondary">{{argument.conclusion}}</a>
            {% else %}
                <a href = "{% url 'wiki:argument' argument.attacked_argument.id %}" class="text-muted">{{argument.attacked_argument}}</a>
            {% endif %}
        </dd>
        {% endfor %}
        {% endif %}
            {% endfor %}
        </div>
        <h2>Low relevance for this Category</h2>
        <div class="well well-sm">
    {% for category in categorylabel.category_set.all %}
        {% if category.relevance < 0.7  %}
        {% for argument in category.argument_set.all %}
       <dd><a href = "{% url 'wiki:argument' argument.id %}"><i  class="fa fa-comment-o" aria-hidden="true"></i></a>
            <span class="text-muted">Regarding that</span>
            <a href="{% url 'wiki:premises' argument.premise_group.id %}"><font color="#ee82ee">{{argument.premise_group}}</font></a>
            {% if argument.isSupportive %}
             <span class="text-success">{{argument.type_text}}</span>
            {% else %}
            <span class="text-danger">{{argument.type_text}}</span>
            {% endif %}
            {% if argument.conclusion %}
            <a href="{% url 'wiki:conclusion' argument.conclusion.id %}" class="text-secondary">{{argument.conclusion}}</a>
            {% else %}
                <a href = "{% url 'wiki:argument' argument.attacked_argument.id %}" class="text-muted">{{argument.attacked_argument}}</a>
            {% endif %}
        </dd>
        {% endfor %}
        {% endif %}
            {% endfor %}
               </div>
    </dl>
    </div>
</body>
</html>

wiki/templates/wiki/detailConclusion.html
<head><!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'wiki/css/style.min.css' %}">
        <meta charset="utf-8">
     <meta name="viewport" content="width=device-width, initial-scale=1"> <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <meta charset="UTF-8">
    <title>{{conclusion}}</title>
</head>
<body>
    <div class="container">
        <h1>{{conclusion}}</h1>
        <dl>
            <p><hr>
            <dd>Attacked By: </dd>
            <div  class="well well-sm">
            {% for argument in conclusion.argument_set.all %}
                {% if argument.isSupportive %}
                {% else %}
                <dt><a href="{% url 'wiki:argument' argument.id %}" class="premise">{{argument.premise_group}}</a></dt>
                {% endif %}
            {% endfor %}
            </div>
        <p><hr>
            <dd>Supported By: </dd>
            <div  class="well well-sm">
            {% for argument in conclusion.argument_set.all %}
                {% if argument.isSupportive %}
                <dt><a href="{% url 'wiki:argument' argument.id %}" class="premise">{{argument.premise_group}}</a></dt>
                {% endif %}
            {% endfor %}
            </div>
         </dl>
    </div>
  </body>
</html>

wiki/templates/wiki/detailDiscussion.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js">
    $(document).ready(function(){
      $('[data-toggle="tooltip"]').tooltip();
    });</script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <meta charset="UTF-8">
    <title>{{issue.issue_title}}</title>
</head>
<body>
    <div class="container">
    <h1>{{issue.issue_title}}</h1>
        <div class="panel-group" id="accordion">
        {% for position in issue.position_set.all %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a data-toggle="collapse" data-parent="#accordion" href="#c{{position.id}}">
                            <h8>{{position}}</h8>
                            <div class="progress">
                                <a href="#" data-toggle="tooltip" data-placement="auto" title="This progressbar represents the acceptance of a position.
                                Red means that the negation of the position is accepted.
                                Orange conveys that there is no real opinion picked by the participants.
                                Green tells us that the position is accepted as it is.">
            {% if position.acceptance_score <= 25 %}
                    <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="{{position.acceptance_score}}" aria-valuemin="0" aria-valuemax="100" style="width:{{position.acceptance_score}}%">
                        </div>
            {% elif position.acceptance_score >= 75 %}
                    <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="{{position.acceptance_score}}" aria-valuemin="0" aria-valuemax="100" style="width:{{position.acceptance_score}}%">
                        </div>
            {% else %}
                    <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="{{position.acceptance_score}}" aria-valuemin="0" aria-valuemax="100" style="width:{{position.acceptance_score}}%">
                        </div>
             {% endif %}</a></div></a></h4>
                </div>
            <div id="c{{position.id}}" class="panel-collapse collapse">
            <div class="panel-body">
                <dl>

            {% for argument in position.argument_set.all %}
                    <dd>
                 <a href = "{% url 'wiki:argument' argument.id %}"><i  class="fa fa-comment-o" aria-hidden="true"></i></a>
                <span class="text-muted">Regarding that</span>
                <a href="{% url 'wiki:premises' argument.premise_group.id %}"><font color="#ee82ee">{{argument.premise_group}}</font></a>
                {% if argument.isSupportive %}
                 <span class="text-success">{{argument.type_text}}</span>
                {% else %}
                <span class="text-danger">{{argument.type_text}}</span>
                {% endif %}
                {% if argument.conclusion %}
                <a href="{% url 'wiki:conclusion' argument.conclusion.id %}" class="text-secondary">{{argument.conclusion}}</a>
                {% else %}
                    <a href = "{% url 'wiki:argument' argument.attacked_argument.id %}" class="text-muted">{{argument.attacked_argument}}</a>
                {%endif%}</dd>
            {% endfor %}</dl>
            </div></div></div>
        {% endfor %}
    </div>
    </div>
</body>
</html>

wiki/templates/wiki/detailKeyword.html
<!DOCTYPE html>
<html lang="en">
<head>
        <meta charset="utf-8">
     <meta name="viewport" content="width=device-width, initial-scale=1"> <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'wiki/css/style.min.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
    <title>{{keywordtext}}</title>
</head>
    <div class="container">
    <h1>{{keywordtext}}</h1>
    <dl>
    {% for keyword in keywordtext.keyword_set.all %}
        {% for argument in keyword.argument_set.all %}
       <dd><a href = "{% url 'wiki:argument' argument.id %}"><i  class="fa fa-comment-o" aria-hidden="true"></i></a>
            <span class="text-muted">Regarding that</span>
            <a href="{% url 'wiki:premises' argument.premise_group.id %}"><font color="#ee82ee">{{argument.premise_group}}</font></a>
            {% if argument.isSupportive %}
             <span class="text-success">{{argument.type_text}}</span>
            {% else %}
            <span class="text-danger">{{argument.type_text}}</span>
            {% endif %}
            {% if argument.conclusion %}
            <a href="{% url 'wiki:conclusion' argument.conclusion.id %}" class="text-secondary">{{argument.conclusion}}</a>
            {% else %}
                <a href = "{% url 'wiki:argument' argument.attacked_argument.id %}" class="text-muted">{{argument.attacked_argument}}</a>
            {%endif%}</dd>
        {% endfor %}</dl>
    {% endfor %}
    </div>
</body>
</html>

wiki/templates/wiki/detailPremises.html
<head><!DOCTYPE html>
<html lang="en">
<head>
        <meta charset="utf-8">
     <meta name="viewport" content="width=device-width, initial-scale=1"> <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <meta charset="UTF-8">
    <title>{{premisegroup}}</title>
</head>
<body>
    <div class="container">
        <h1>{{premisegroup}}</h1>
        <dl>
        <p><hr>
            <dd>Questions: </dd>
            <div  class="well well-sm">
            {% for argument in premisegroup.argument_set.all %}
                {% if argument.isSupportive %}
                {% else %}
                {% if argument.conclusion %}
            <dt><a href="{% url 'wiki:argument' argument.id %}" class="text-secondary">{{argument.conclusion}}</a></dt>
                {% else %}
            <dt><a href="{% url 'wiki:argument' argument.id %}" class="text-secondary">{{argument.attacked_argument}}</a></dt>
                {% endif %}
                {% endif %}
            {% endfor %}
            </div>
        <p><hr>
            <dd>Supports: </dd>
            <div  class="well well-sm">
            {% for argument in premisegroup.argument_set.all %}
                {% if argument.isSupportive %}
                <dt><a href="{% url 'wiki:argument' argument.id %}" class="text-secondary">{{argument.conclusion}}</a></dt>
                {% endif %}
            {% endfor %}
            </div>
        </dl>
    </div>
  </body>
</html>

wiki/templates/wiki/index.html
<!DOCTYPE html>
<html lang="en">
<head>
        <meta charset="utf-8"
     <meta name="viewport" content="width=device-width, initial-scale=1"> <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <meta charset="UTF-8">
    <title>Issues</title>
</head>
<body>
<div class="container">
    <h2>Issues</h2>
    {% if discussion_topics %}
    <dl>
    {% for issue in discussion_topics %}
        <div class="well">
            <a href="{% url 'wiki:issue' issue.id %}"><dt>{{ issue.issue_title }}</dt></a>
                <dd>{{ issue.issue_info }}</dd>
        </div>
    {% endfor %}
    </dl>
{% else %}
    <p>No Issues are available.</p>
{% endif %}
    <table>
<form action="update" method="GET">
    <button class="btn btn-primary" onclick="location.href={% url 'wiki:update' %}">Update</button>
</form>
    <form action="search" method="GET">
    <button class="btn btn-primary" onclick="location.href={% url 'wiki:search' %}">Search</button>
</form></table>
</div>

</body>

wiki/templates/wiki/paginator.html
<!-- https://simpleisbetterthancomplex.com/tutorial/2016/08/03/how-to-paginate-with-django.html -->

<ul class="pagination">
    {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="enabled"><span>&raquo;</span></li>
    {% endif %}
</ul>

wiki/templates/wiki/searchField.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'wiki/css/style.min.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <title>Search</title>
</head>
<body>
<div class="container">

    <h2>Arguments</h2>

    <form class="form-inline" action="" method="GET">
        {{ form }}
        <button class="btn btn-primary" type="submit">Search</button>
        </fieldset>
    </form>

    <table class="table table-bordered table-condensed">
        <tr>
            <th>Argument</th>
            <th>Date</th>
            <th>Supportive</th>
            <th>Language</th>
            <th>Argument Acceptance</th>
        </tr>
        {% for object in object_list %}
        <tr>
            <td><a href = "{% url 'wiki:argument' object.id %}"><i  class="fa fa-comment-o" aria-hidden="true"></i></a>
                <span class="text-muted">Regarding that</span>
                <a href="{% url 'wiki:premises' object.premise_group.id %}" class="premise">{{object.premise_group}}</a>
                {% if object.isSupportive %}
                 <span class="text-success">{{object.type_text}}</span>
                {% else %}
                <span class="text-danger">{{object.type_text}}</span>
                {% endif %}
                {% if object.conclusion %}
                <a href="{% url 'wiki:conclusion' object.conclusion.id %}" class="text-secondary">{{object.conclusion}}</a>
                {% else %}
                    <a href = "{% url 'wiki:argument' object.attacked_argument.id %}" class="text-muted">{{object.attacked_argument}}</a>
            {% endif %}</td>
            <td>{{object.date}}</td>
            <td>{{object.isSupportive}}</td>
            <td>{{object.lang}}</td>
            <td>{{object.argument_acceptance}}</td>
        </tr>
        {% endfor %}
    </table>

    {% if is_paginated %}
        {% include "wiki/paginator.html" %}
    {% endif %}

</div>

</body>
</html>